git -C fluxions      push
git -C fluxions-gte  push
git -C fluxions-base push
git -C fluxions-ssg  push
git -C fluxions-renderer push
git -C fluxions-renderer-gles30 push
git -C damselfish    push
git -C hatchetfish   push
git -C starfish      push
git -C unicornfish   push
git -C viperfish     push
git -C ssphh         push
git -C ssphh-data    push
