git -C fluxions      pull
git -C fluxions-gte  pull
git -C fluxions-base pull
git -C damselfish    pull
git -C hatchetfish   pull
git -C starfish      pull
git -C unicornfish   pull
git -C viperfish     pull
git -C imgui         pull
git -C ssphh         pull
git -C ssphh-data    pull
